[versions]
agp = "8.13.0"
kotlin = "2.2.21"
#coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
exifinterface = "1.4.1"
#lifecycleRuntimeKtx = "2.9.4"
#activityCompose = "1.11.0"
#composeBom = "2025.10.00"#2024.09.00
#material = "1.13.0"
[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.1" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version = "1.5.1" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version = "1.5.1" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version = "1.5.1" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version = "1.5.1" }
google-material = { group = "com.google.android.material", name = "material", version = "1.13.0" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version = "1.9.4" }#1.5.0
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version = "1.9.4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.4.0" }#1.1.1
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version = "1.9.4" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }

#androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
#androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
#androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
#androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
#androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
#androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
#androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
#androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
#androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
#androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
#androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

